### ISSUE TITLE
ReachabilitySample code may cause your app to fail the Apple approval process due to IPv6 requirement

### ISSUE THREAD

**Issue by trevoriancox** [xamarin/ios-samples#106]
Has hard-coded IPv4 addresses. See https://blog.xamarin.com/making-your-ios-apps-ipv6-ready/

**Comment by olegoid** [comment]
Thanks @trevoriancox! Should be fixed in 8386893

**Comment by gijsstegehuis** [comment]
@olegoid your fix in 228de75 solves the IPv6 issue, but now it stopped working on IPv4 networks.

**Comment by jamesmontemagno** [comment]
I actually don't think they had to be changed at all. These actually are whitelisted IPs that Apple will accept. See: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/11

**Comment by trevoriancox** [comment]
Maybe Apple's testing was flawed, but updating from this to Connectivity Plugin v2.x (not just 1.x) seems to have resolved our app approval issues.
