### ISSUE TITLE
Reachability - Remove AdHoc TEst /reachabilityForLocalWiFi

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/ios-samples#118]
Per apple docs this will no longer work when on a local wifi :(

https://developer.apple.com/library/content/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11

Fixed this inside connectivity plugin

**Comment by conceptdev** [comment]
for context see https://github.com/xamarin/ios-samples/issues/106

@jamesmontemagno is this the change you mean?
https://github.com/jamesmontemagno/ConnectivityPlugin/blob/a1e9f18c525782d0c87635b9e743028d15a82a29/src/Connectivity.Plugin.iOSUnified/Reachability.cs#L138-L176

**Comment by jamesmontemagno** [comment]
Yup! Was it removed in #106? This needs to be removed: https://github.com/xamarin/ios-samples/blob/master/ReachabilitySample/reachability.cs#L61-L73
