### ISSUE TITLE
Reminder is not working 

### ISSUE THREAD

**Issue by Resham143** [xamarin/ios-samples#133]
I tried several time to use this sample to add reminder in my app but reminder is not working .

**Comment by olegoid** [comment]
@Resham143 could you provide more information about sample you're using, reproduction steps and your setup?

**Comment by Resham143** [comment]
I used the sample provided by Xamarin in their guide. But It did not work.

**Comment by olegoid** [comment]
Thanks @Resham143. However, I still don't understand what sample you're trying to use and what guide you're reading.

**Comment by Resham143** [comment]
Issue is fixed. I was using wrong method.

**Comment by olegoid** [comment]
Thanks @Resham143, I'm closing the ticket.
