### ISSUE TITLE
Cannot Run in Visual Studio

### ISSUE THREAD

**Issue by ljunquera** [xamarin/ios-samples#137]
This is not likely a bug but did not know where to post. I run the project in Visual Studio and the iPhone emulator comes up but the watch emulator does not.

**Comment by olegoid** [comment]
Hello @ljunquera could you file a bug to our Bugzilla: https://bugzilla.xamarin.com/

Please provide us with reproduction steps and details about your machine setup.

Closing this issue for now. Feel free to reopen.
