### ISSUE TITLE
AVCustomEdit

### ISSUE THREAD

**Issue by Pointy-hair** [xamarin/ios-samples#154]
IOS 10.2.1

The transitions do not work, both diagonal wipe and cross dissolve do not render correctly. The issue with diagonal wipe is obvious, however, the cross dissolve is more subtle as the colours are not correct in the transition as the flowers are green and the jump to purple once the second video is fully in, also green leaves go purple in the transition. Work correctly in the sample downloaded from Apple and run in xcode on an iMac.    

Also noticed in both the Apple version and Xamarin that the video can stop in the middle on the 2/3 playing.

Fantastic example but quite buggy, would love for someone with the skills to look at this.
Thanks

**Comment by conceptdev** [comment]
This sample has now been updated, hopefully addressing all these concerns. PR linked above.
