### ISSUE TITLE
Homekit sample crashes

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [xamarin/ios-samples#162]
Seems that it doesn't like that I use "eve" in my HomeKit. 

Documented GUID here
https://gist.github.com/gomfunkel/b1a046d729757120907c

Error screenshot attached.

<img width="1196" alt="screen shot 2017-04-24 at 8 58 06 pm" src="https://cloud.githubusercontent.com/assets/606120/25364642/d0506482-2931-11e7-9124-c1890adcae6c.png">

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
