### ISSUE TITLE
[HomeKitIntro] Sample is not working in iOS 10.2 simulator

### ISSUE THREAD

**Issue by SamRizvi** [xamarin/ios-samples#164]
I tried to search and add accessory, unfortunately it showing a timeout when i tried to add the accessory. Please guide me.

**Comment by conceptdev** [comment]
You do not say which sample is not working. Please add a link.

**Comment by SamRizvi** [comment]
Xamarin HomeKitIntro sample app

**Comment by rolfbjarne** [comment]
I don't get a timeout, but I get a `Couldn't add Accessory: Home couldn't connect to this accessory.` error, both in the simulator and on device.

I don't know if this is a problem with the sample or with Apple's API / the HomeKit Accessory Simulator.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
