### ISSUE TITLE
Missing iOS Binding Project

### ISSUE THREAD

**Issue by sethom** [xamarin/ios-samples#165]
According to the Xamarin website, this sample project contains 3 source projects:

> This sample consists of three distinct source projects:
> 
> Xcode Project in Objective-C
> MonoTouch Binding classes
> MonoTouch Sample Project

I can't find the XMBindingLibrary project.

**Comment by conceptdev** [comment]
Is this the project you are looking for?

https://github.com/xamarin/ios-samples/tree/master/BindingSample/src/binding

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
