### ISSUE TITLE
CustomPaymentObserver crashes

### ISSUE THREAD

**Issue by ivanicin** [xamarin/ios-samples#166]
With the message:

Failed to marshal the Objective-C object 0x1386b960 (type: App_CustomPaymentObserver). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'App.CustomPaymentObserver' does not have a constructor that takes one IntPtr argument). Additional information: Selector: paymentQueue:updatedTransactions: Method: App.CustomPaymentObserver:UpdatedTransactions (StoreKit.SKPaymentQueue,StoreKit.SKPaymentTransaction[]) 

As far as I can read you need to add another constructor with IntPtr argument.

**Comment by rolfbjarne** [comment]
Exactly which sample was this, and what did you do in the sample to cause this?

**Comment by ivanicin** [comment]
It was based on this sample: https://github.com/xamarin/ios-samples/tree/master/StoreKit

Not sure exactly how it crashed as it was report from the AppCenter.

As I have switched to https://github.com/jamesmontemagno/InAppBillingPlugin/issues , I am not using that and I don't see those exceptions so I guess it is the best to close the bug, still if you think there is something that could be fixed just ask I'll help as much as I can.
