### ISSUE TITLE
WatchOS WatchConnectivity not working in Release Mode

### ISSUE THREAD

**Issue by rduverna** [xamarin/ios-samples#178]
In my project were implementing a WatchOS project that communicates with the companion app using WatchConnectivity.   I've used the WatchConnectivity project as references  and was able to get my app and watch to run perfectly during testing.  However, when pushing our application to Testflight and the App Store in release mode, the watch application fails once it receive a message from the companion app or when it tries to send a message.  I've tried many different options to get this working, but was unsuccessful.  I wanted to know if anyone has successfully implemented WatchConnectivity and has release in App store with any problems.

project: ios-samples/watchOS/WatchConnectivity/

**Comment by rolfbjarne** [comment]
Have you tried the WatchConnectivity sample itself (without modifications)? If you change the bundle IDs (and create the required provisioning profiles), you should be able to build for release and release to yourself using TestFlight to see if it's something in the sample or in your code.

Also it would be helpful to know exactly how it fails (error message? crash? just doesn't work?)

**Comment by spouliot** [comment]
We have not received the requested information. If you still have this issue please provide them and re=open the issue. Thanks!
