### ISSUE TITLE
Need Sample iOS apps to test on Appium

### ISSUE THREAD

**Issue by Ethesh** [xamarin/ios-samples#180]
Hi All,

I am learning Appium, so i need sample apps to learn and experiment. Could anyone tell me where i will get.

Thanks

**Comment by conceptdev** [comment]
try
https://docs.microsoft.com/en-us/mobile-center/test-cloud/preparing-for-upload/appium
http://appium.io

**Comment by Ethesh** [comment]
I need Apps (iOS apps). which i can run using appium
