### ISSUE TITLE
When zooming zoompart is not correct rendering

### ISSUE THREAD

**Issue by eL-Prova** [xamarin/ios-samples#181]
Downloaded latest version, run the example.
But when I zoom the zoomed part is shown on strange places.
Should the SubView not be removed?

**pageRect = new CGRect (pageRect.X, pageRect.Y, pageRect.Width * PdfScale, pageRect.Height * PdfScale);**
This should be: **pageRect = new CGRect (0, 0, pageRect.Width * PdfScale, pageRect.Height * PdfScale);**

```
void ReplaceTiledPDFView (CGRect rect)
		{
			// Create a new tiled PDF View at the new scale
			var tiledPDFView = new TiledPdfView (rect, PdfScale); //rect instead of Frame
			tiledPDFView.Page = page;

// Add the new TiledPDFView to the PDFScrollView.
			AddSubview (tiledPDFView);
			TiledPDFView = tiledPDFView;
		}

```
This makes it a little bit better, but my zoomed part is now rendered under the original

Edit 2: ZoomingStarted and ZoomingEnded can be removed, the zoom is in that case working correctly

**Comment by mykyta-bondarenko-gl** [comment]
It's already fixed. You can check the updated sample [here](https://github.com/xamarin/ios-samples/tree/master/ZoomingPdfViewer)
@eL-Prova  ^
