### ISSUE TITLE
reachability sample InternetConnectionStatus not working

### ISSUE THREAD

**Issue by heebaek** [xamarin/ios-samples#188]
InternetConnectionStatus always return not reachable.
i tested it with iPhone 7Plus, iOS 10.3.3, VS for mac, xamarin iOS.

it works after remove ipAddress.MapToIPv6() from IsNetworkAvailable function.

var ipAddress = new IPAddress(0);
defaultRouteReachability = new NetworkReachability(ipAddress); 

please check this issue.

**Comment by ilpoimigee** [comment]
Having exactly similar behavior. Did not yet try if that  ipAddress.MapToIPv6() removal would work. 

Tested on iPhoneSimulator and 6s iOS 10.3.3.

**Comment by supershowwei** [comment]
i have the same problem. i tested it with iPhone 5s iOS 11.2.6.

--not work--
defaultRouteReachability = new NetworkReachability(ipAddress.MapToIPv6());

--work--
defaultRouteReachability = new NetworkReachability(ipAddress);

**Comment by FinHorsley** [comment]
@mykyta-bondarenko-gl Should this issue now be closed?

**Comment by mykyta-bondarenko-gl** [comment]
hi @FinHorsley. I think - yes, it should be closed, thanks for reminding
