### ISSUE TITLE
Failed to deploy CollectionViewTransition

### ISSUE THREAD

**Issue by Jerome2606** [xamarin/ios-samples#192]
Hello,

I tried to check about this example CollectionViewTransition but it failed to deploy on my simulator:

error HE0046: Failed to install the app 'com.xamarin.CollectionViewTransition' on the device 'iOS 11.0 (15A8401) - iPhone 8': Coudn't communicate with a helper application.

Did I miss something before deploying it ?

**Comment by rolfbjarne** [comment]
This is usually fixed by closing and relaunching Xcode, simulators and Visual Studio (for Mac).

If that doesn't work, try rebooting the Mac.

If it still fails, feel free to reopen this issue and we'll have a deeper look.
