### ISSUE TITLE
Warnings with Hello, iOS (Single view)

### ISSUE THREAD

**Issue by sayedihashimi** [xamarin/ios-samples#202]
In the dogfood build I'm seeing the following warnings.

![image](https://user-images.githubusercontent.com/1283154/34786957-aa8fba3c-f603-11e7-9dbb-e53d75c7d36d.png)

**Comment by bradumbaugh** [comment]
Thanks for the call-out, @sayedihashimi. Checked in a fix for this. /cc @conceptdev
