### ISSUE TITLE
ImageInverterExtn sample does not work.

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/ios-samples#213]
ImageInverter sample isn't working anymore but seems to be unrelated to Xamarin.iOS, the native Apple sample this is based on also does not work so there is a high chance that there were some changes in either iOS or Xcode 9 (or both) that are breaking it. Already tested bot ours and Apple's sample down to d15-4 and I get the same results.

Sample with issue:
https://github.com/xamarin/ios-samples/tree/master/ios8/ImageInverter

Original Issue report:
https://github.com/xamarin/xamarin-macios/issues/3371

quoting original report:

### Steps to Reproduce

 1. Download and open https://developer.xamarin.com/samples/monotouch/ios8/ImageInverter/ImageInverter.zip
2. Set iOS Deployment target to 11.0 or higher in both main and extension app
3. Set Extension App as startup project and rebuild the project
4. Deploy it in iOS simulator 
5. Open ImageInverter app in iOS simulator 
6. Enable ImageInverterExtn App in it

### Expected Behavior
ImageInverterExtn App should launch in iOS Simulator and Image should
be Inverted
 
### Actual Behavior
Blank screen is displayed when ImageInverterExtn loaded 
Screencast: https://www.screencast.com/t/BweketBj

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
