### ISSUE TITLE
[XI]"SamplePhotoApp" - inconsistent crash during live photo edits

### ISSUE THREAD

**Issue by bradumbaugh** [xamarin/ios-samples#217]
- On both the iOS10/SamplePhotoApp and iOS11/SamplePhotoApp, seeing crashes when editing a live photo (applying Sepia/Chrome filter)
- Happens inconsistently
- Tested on iPhone SE, iOS 11.2.6

**Comment by rolfbjarne** [comment]
I tried this on an iPhone X with iOS 12.2, and I couldn't see any crashes after tried for a while, so I'm closing this.

If it still happens, please add information about the crash itself and reopen the issue.
