### ISSUE TITLE
[MonkeyNotify] verify sample works as expected

### ISSUE THREAD

**Issue by conceptdev** [xamarin/ios-samples#224]
For https://github.com/MicrosoftDocs/xamarin-docs/issues/109

**Comment by jessejiang0214** [comment]
Hi, 
I meet the same issue, I found NotificationService never be called in that sample and I didn't find any document to resolve that.

**Comment by unamed000** [comment]
Have the same issue ....

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
