### ISSUE TITLE
Fox2 - tvOS - Congratulations

### ISSUE THREAD

**Issue by bradumbaugh** [xamarin/ios-samples#235]
After "winning" the Fox2 game by releasing the other foxes from behind the locked door, on macOS and iOS there's a "congratulations" graphic that appears. However, this graphic doesn't appear on tvOS.

**Comment by mykyta-bondarenko-gl** [comment]
Hi @bradumbaugh. 
The "congratulation" graphic doesn't appear because it's disabled for tvOS application [in code](https://github.com/xamarin/ios-samples/blob/master/ios11/Fox2/Fox2.Shared/GameController.cs#L1379). It intended to show how a developer can optimize an application.

**Comment by bradumbaugh** [comment]
Ah, my mistake - thanks!
