### ISSUE TITLE
Fix keyboard/animation issues in Chat sample

### ISSUE THREAD

**Issue by bradumbaugh** [xamarin/ios-samples#237]
See [thread](https://github.com/xamarin/ios-samples/commit/1b9192eb7dd452ab1db9cb55e567fb44083ec73c#commitcomment-28722062)

- When using the software keyboard, the keyboard appears but there's no text entry box
- Sample crashes when enter is pressed

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
