### ISSUE TITLE
ERROR ITMS-90022:"Missing requirted icon file.The bundle does not contain an app icon for iphone/ipod Touch of exactly 120*120 pixels,in .png formatfor version>=10.0"

### ISSUE THREAD

**Issue by DnyaneshWahiley** [xamarin/ios-samples#271]
Hello all i provided my own bundle id and try to upload this ipa on app store through app loader it gives me this error
current target ios version is = 11.0

**Comment by bradumbaugh** [comment]
Hi @DnyaneshWahiley, sorry to hear you've hit a snag.

Unfortunately, this repository is intended for issues with the documentation. For support, please use **Report a Problem** in [Visual Studio 2017](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) or [Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem) to report issues in [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

That said, from the description of your error, it sounds like perhaps your asset catalog needs to include a missing icon. Please see [this doc](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/app-icons?tabs=vsmac) for details.

Hope this helps!
