### ISSUE TITLE
Label on Apple Watch is not updated

### ISSUE THREAD

**Issue by kolegs** [xamarin/ios-samples#279]
Hi,

Tried this example https://github.com/xamarin/ios-samples/tree/master/watchOS/WatchConnectivity

When sending data from iPhone to Apple Watch label on Watch is not updated. I can confirm that data is sent. Also sending data from watch do iPhone works and label is updated as expected.

Tested on iPhone 5s iOS 12.0 and apple watch generation 1(A1554) watchOS 4.3.2
Simulator also doesn't update label on iPhone XS and Apple Watch 4 - 40mm

**Comment by b099l3** [comment]
I can take a look at this, created the sample years ago but I'll update it for WatchOS 5

**Comment by b099l3** [comment]
I ran this against the simulator and it worked as expected. Do you have any logs?

**Comment by mykyta-bondarenko-gl** [comment]
Hi @kolegs, try a new one sample
https://github.com/xamarin/ios-samples/tree/master/watchOS/SimpleWatchConnectivity

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
