### ISSUE TITLE
Xamarin IOS info.plist Device Orientation Changes After Save

### ISSUE THREAD

**Issue by MonkeyLucas** [xamarin/ios-samples#287]
Every time I go in to Info.plist in order to lock the app to Portrait orientation and save, my changes aren't saved.
For more detail you can access [https://stackoverflow.com/questions/52747057/windows-vs-xamarin-ios-info-plist-device-orientation-changes-after-save](url)

**Comment by conceptdev** [comment]
@MonkeyLucas this sounds like a product problem, which should be raised on [Developer community](https://developercommunity.visualstudio.com/) or on the [open source product repo for Xamarin.iOS](https://github.com/xamarin/xamarin-macios).

These issues are monitored only for problems with the samples themselves.
