### ISSUE TITLE
watchkit samples don't work

### ISSUE THREAD

**Issue by rocketbob** [xamarin/ios-samples#291]
Getting the following exception when trying to compile the iOS watch samples:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.WatchApp.Common.targets(3,3): Error: Xcode 10 does not support watchOS 1 apps. Either upgrade to watchOS 2 apps, or use an older version of Xcode. (WatchApp)

Latest of everything installed, XCode 10.

**Comment by rolfbjarne** [comment]
The samples in the [watchOS](https://github.com/xamarin/ios-samples/tree/master/watchOS) directory have been updated to use watchOS 2+.
