### ISSUE TITLE
Unable to load project in my physical iPhone Device 

### ISSUE THREAD

**Issue by arpanpatel94** [xamarin/ios-samples#295]
Hey Tech Team,

I want to try a Apple Health services in my iOS Application by using Xamarin. So, I Downloaded a demo app that you are Uploaded in Github as  **_[IntroToHealthKit](https://github.com/xamarin/ios-samples/tree/master/ios8/IntroToHealthKit)_**

I'm trying to load that sample HealthKit GitHub Demo on my MacBook But, it shows me Error & says **(kAMDIncorrectArchitectureError).** 

It's a crucial needed to run that demo for test before implementing. Here i'm attaching some **Error Logs** and some **screen shots** below.

**_Error Logs :_**

```
IncorrectArchitecture: Failed to find matching arch for 64-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.lBNtCz/extracted/HKPermissions2.app/HKPermissions2
error MT1006: Could not install the application '/Users/jaysanjay/Desktop/IntroToHealthKit/HKWork/bin/iPhone/Debug/HKPermissions2.app' on the device 'jay’s iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe8000087 (kAMDIncorrectArchitectureError).

Application could not be uploaded to the device.
```

**_Screen Shot :_**

![screen shot 2018-11-04 at 3 43 49 pm](https://user-images.githubusercontent.com/44098923/47962822-88ab6080-e048-11e8-90c7-2cb990010184.png)

## Help me, Guys.

**Comment by FinHorsley** [comment]
@arpanpatel94 Did you manage to get this resolved?

**Comment by rolfbjarne** [comment]
This is because the sample project is configured to only build for 64-bit, and you have a 32-bit device.

You can make it build for 32-bit if you select `ARMv7` as the `Supported architecture` in the project's iOS Build options.
