### ISSUE TITLE
SFSpeechRecognizer crash on iOS 12

### ISSUE THREAD

**Issue by risingworld777** [xamarin/ios-samples#297]
SpeakToMe sample worked well before iOS 12.
But I got crash from the users who use iOS 12. Here is crash message.

> com.apple.coreaudio.avfaudio Reason: required condition is false: format.sampleRate == hwFormat.sampleRate

I guess there is problem in getting recording format in below line.
https://github.com/xamarin/ios-samples/blob/c1f4e206e224353c42311de6e59e722298aee3c9/ios10/SpeakToMe/SpeakToMe/ViewController.cs#L107
It seems it requires different recording format as per phone model in iOS 12.

**Comment by mykyta-bondarenko-gl** [comment]
Hi @risingworld777. Do you have this problem now?

**Comment by rolfbjarne** [comment]
This works fine for me, I tried both the simulator and an iPhone X with iOS 12.2

I'm closing this for now. If this is still a problem, please attach the complete build log, and indicate exactly which device you ran this on.
