### ISSUE TITLE
not deploying

### ISSUE THREAD

**Issue by ameet20** [xamarin/ios-samples#359]
Hello,

I tried to check about this example CollectionViewTransition but it failed to deploy on my simulator:

error `HE0046: Failed to install the app 'com.xamarin.CollectionViewTransition' on the device 'iOS 11.0 (15A8401) - iPhone 8'`: Coudn't communicate with a helper application.

Did I miss something before deploying it ?

**Comment by rolfbjarne** [comment]
This is usually something in Apple's toolchain that ends up confused, usually it's fixed by rebooting the Mac.

I'm closing this issue since it's probably not an issue with any of the samples. Feel free to reopen if any the samples continue to fail, and we'll have a deeper look.
