### ISSUE TITLE
Image plane incorrect positioning in ARKitSample project

### ISSUE THREAD

**Issue by andynorton** [xamarin/ios-samples#375]
In ios11/ARKitSample/ARKitSample/GameViewController.cs

After running the code, it works as expected until I tap on the screen, the gesture recognize event is called and it works fine the first time - I get a plane node with a snapshot of the screen. But when this is called the second time, instead of creating a new node at the location of the second tap, it overlaps the initial child node.

The behaviour is different from the original version demoed here -  https://youtu.be/LLRweyZ1KpA?t=1380

Example behaviour after a few screen taps:
![IMG_3058](https://user-images.githubusercontent.com/647251/58461567-e3f98900-8127-11e9-8076-e52bf0cdc751.jpg)

**Comment by chamons** [comment]
I can confirm that there appears to be something wrong with this sample. Tapping did _nothing_ for me, despite the fact that we are hitting HandleTap

**Comment by andynorton** [comment]
The initial positioning of the photo node should be just in front of the camera, but with this sample it's probably putting it just behind the camera. 

I think we're missing some sort of position settings after
`planeNode.Transform = SCNMatrix4.Mult(cameraTranslation, translation);

I can kind-of get a solution with
`planeNode.Transform = SCNMatrix4.Mult(cameraTranslation, translation);
`planeNode.Position = cameraTranslation.Column3.Xyz;

But it needs some additional work to rotate the node into the same position as the ARCamera.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
