### ISSUE TITLE
Reachability sample issue

### ISSUE THREAD

**Issue by alphagamer7** [xamarin/ios-samples#384]
Regarding this - https://github.com/xamarin/ios-samples/tree/master/Reachability

For internet connectivity check,
I have used  as in the example but the event only gets fired once, from when I Connect -> Disconnect. When I reconnect back, the event doesn't get fired. Any idea why?

Simulator iOS 12.4
macOS Mojave Version 10.14.6

**Comment by whitneyschmidt** [comment]
Thank you for your feedback!

Have you tried the sample from Apple? Does it show the same behavior?

Could you please post exact steps to reproduce your issue if so?

**Comment by alphagamer7** [comment]
Also similar thing happens when using with [Xamarin.Essesntials](https://github.com/xamarin/Essentials/issues/901) 
So I tried the [sample iOSReachabilityTestARC](https://github.com/tonymillion/Reachability), and this was the results

<img width="578" alt="Screen Shot 2019-09-07 at 8 25 20 AM" src="https://user-images.githubusercontent.com/17358908/64469016-12d0c380-d149-11e9-9bdf-0161f9b513d7.png">

Note: Checked internet connection through wifi

I have reconnected through wifi, but it only shows local wifi connection available as shown in the screenshots

**Comment by alphagamer7** [comment]
@whitneyschmidt Any updates on the issue?

**Comment by chamons** [comment]
Strange, I just tested it and I see wifi show up after dropping and returning.

Can you post exact steps to reproduce?

**Comment by alphagamer7** [comment]
@chamons Steps to reproduce
1. Run [app](https://github.com/tonymillion/Reachability) with internet connection( Similar happens for x[amarin.essentials ](https://github.com/xamarin/Essentials/issues/901)as well)
2. After app is loaded, turn wifi off
The following screen shows
![image](https://user-images.githubusercontent.com/17358908/65714135-26bc7500-e0b8-11e9-8d7b-33cab12c84fa.png)
3. Turn Wifi on
The following screen is shown. Note: no internet connection although wifi block says reachable.
![image](https://user-images.githubusercontent.com/17358908/65714227-50759c00-e0b8-11e9-83fa-006c3f3e6a4f.png)

**Comment by alphagamer7** [comment]
According to this https://github.com/xamarin/Essentials/issues/855 testing in simulator doesn't yield correct results, confirmed by testing with physical device, works as expected.

**Comment by spouliot** [comment]
> testing with physical device, works as expected.

closing
