### ISSUE TITLE
SoupChef sample doesn't start on iOS 13

### ISSUE THREAD

**Issue by pdecostervgls** [xamarin/ios-samples#388]
After upgrading my iPhone to iOS 13(.1.2) the SoupChef sample app fails to start. No messages in console either.

**Comment by mandel-macaque** [comment]
Can you please provide the full information of the xamarin development environment you have. 

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by spouliot** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
