### ISSUE TITLE
BindingSample is incomplete

### ISSUE THREAD

**Issue by macu** [xamarin/ios-samples#39]
The binding capabilities of Xamarin/MonoTouch are a key feature for developers using third-party iOS SDKs, typically written in Obj-C. Very little Obj-C code is presented in the [official docs](http://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/) to correspond to the C# example code, which presents problems for developers using Xamarin who have not previously worked in Obj-C.

It would be great if the monotouch-samples/BindingSample project were more of a complete demonstration of binding to all kinds of Obj-C constructs, as outlined in the official docs, with corresponding Obj-C code for the C# binding examples (perhaps have the Obj-C definitions in comments before the C# code that binds to them, for comparison).

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
