### ISSUE TITLE
Opening a URL/File in app Crashes in iOS13 Xamarin

### ISSUE THREAD

**Issue by alphagamer7** [xamarin/ios-samples#390]
Prior to iOS 13, my app handled a specific URI type, and it worked just fine. The openURL override in AppDelegate would get triggered as normal.
As soon as I try on iOS 13, after hitting 'open in my app' the app crashes immediately. I don't even hit a breakpoint inside "openURL". The whole stack trace is native code, so I'm not even sure where to begin with this one.
(copied from stackoverflow [question](https://stackoverflow.com/questions/58370852/opening-a-url-file-in-app-crashes-in-ios13-xamarin)) by [Kikootwo](https://stackoverflow.com/users/6641200/kikootwo) since I am facing same issue.

About Visual Studio - 

=== Visual Studio Community 2019 for Mac ===

Version 8.3.3 (build 8)
Installation UUID: 14dc218b-d2f5-4137-b7f5-c252b4c4c6e4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803030008
Git revision: fb0d3af49f0ea88661a4f469b9dfd1018dc099cd
Build date: 2019-10-10 10:53:35+00
Build branch: release-8.3
Xamarin extensions: 3f8e699ba26ed5f69b7a6466ba679f4a328fadb4

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by whitneyschmidt** [comment]
@alphagamer7 Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs and solution files. The solution files are what will allow us to repro the issue and investigate.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by alphagamer7** [comment]
Strangely it works as expected now. Didn't do any changes to code.
