### ISSUE TITLE
Not receiving callbacks in  'Refreshing and Maintaining Your App Using Background Tasks'

### ISSUE THREAD

**Issue by jithinmadathil07** [xamarin/ios-samples#392]
Regarding - https://github.com/xamarin/ios-samples/tree/master/ios13/RefreshingAndMaintainingYourAppUsingBackgroundTasks

I have tried to run xamarin 'Refreshing and Maintaining Your App Using Background Tasks' sample on iphone7(iOS 13.2) using VS2019 for mac. But I am not getting any callback for BGAppRefreshTask or BGProcessingTask in background.

I have enabled UIbackground modes in Info.plist(fetch and processing).
Added BGTaskSchedulerPermittedIdentifiers key and uniques task ids to Info.plist
Tried diffrent EarliestBeginDate intervals(5,15,30 minutes).Used local notification to show the callback.

I tried with native swift sample code also.There  I was able to receive the callbacks.

So do I need to add anything else for getting callback in xamarin?

Configuration
OS:Catalina 10.15
iphone version:iphone 7(iOS 13.2)

**Comment by chamons** [comment]
I believe I have the background tasks firing with this change:

https://github.com/xamarin/ios-samples/pull/393/files

which is noted in the [readme instructions](https://github.com/xamarin/ios-samples/blob/master/ios13/RefreshingAndMaintainingYourAppUsingBackgroundTasks/README.md) as something you need to do.

**Comment by sandeep-eroad** [comment]
This is not working for me even in a small test app. Have a look at the attached sample app.
[TestApp.zip](https://github.com/xamarin/ios-samples/files/5839910/TestApp.zip)

**Comment by comfr3ak** [comment]
Having a similar problem with the task never firing. Have followed this precisely line for line and regardless of how I treat the iPad, the task will never fire. I have assured all the settings are enabled, Background Refresh is enabled on the device for my app, the info.plist keys are added. Never fires. Running iPad Pro with iOS 14.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
