### ISSUE TITLE
SiriKitSample/TaksNotes is not showing UI

### ISSUE THREAD

**Issue by jhermsen** [xamarin/ios-samples#394]
The UI is not showing on the SirikitSample: https://github.com/xamarin/ios-samples/tree/master/ios11/SiriKitSample

The app is building without any issue/error to the device, but when the app starts the scree is just blank.

**Comment by chamons** [comment]
It appears to work for me on  simulator.

![image](https://user-images.githubusercontent.com/6392201/69763951-69d8aa00-1134-11ea-8132-fa2979e54cf3.png)

Can you please attach build log / what version of the SDK / what version of the Xcode you are using. Does it work on device but not sim (or vice versa)?

**Comment by jhermsen** [comment]
Hadn't tried in in the sim yet, but sim does work and show the content. Also works using sim iPad Air 2 - 13.2.

But when I deploy it to an actual device iPad Air 2 - 13.2.3 it has a blank display.

In regards to versions:
XCode: 11.2.1
VS2019: 16.3.10
Xamarin: 16.3.0.281
Xamarin IOS SDK: 13.6.0.12
Mono (Mac): 6.4.0.208

Debug output shows the following:
`
Loaded assembly: /private/var/containers/Bundle/Application/469D205B-8BAA-4F1B-9F61-469ADFFCA0E2/TasksNotes.app/System.Core.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/469D205B-8BAA-4F1B-9F61-469ADFFCA0E2/TasksNotes.app/System.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/469D205B-8BAA-4F1B-9F61-469ADFFCA0E2/TasksNotes.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/469D205B-8BAA-4F1B-9F61-469ADFFCA0E2/TasksNotes.app/Xamarin.iOS.dll [External]
Thread started:  #2
Loaded assembly: /private/var/containers/Bundle/Application/469D205B-8BAA-4F1B-9F61-469ADFFCA0E2/TasksNotes.app/TasksNotes.exe
Resolved pending breakpoint at 'ViewController.cs:39,1' to void TasksNotes.ViewController.<>c.<ViewDidLoad>b__1_0 (Intents.INSiriAuthorizationStatus status) [0x0005a].
2019-11-28 10:10:40.380 TasksNotes[316:3138932] SiriKit Authorized
`

**Comment by chamons** [comment]
After swapping to a provisioning profile w\ SiriKit enabled, I can confirm the white screen on device.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
