### ISSUE TITLE
I think we can safely remove this ios-sample from the Xamarin repository now

### ISSUE THREAD

**Issue by gcadmes** [xamarin/ios-samples#397]
Seven years old, and now is meaningless.

**Comment by chamons** [comment]
Which sample in particular? 

We tend to keep older samples, even when not up to date, as they can be good examples of using a particular API.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
