### ISSUE TITLE
how fix the bug？

### ISSUE THREAD

**Issue by coffice12** [xamarin/ios-samples#398]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.WatchApp.Common.targets(3,3): Error: Xcode 10 does not support watchOS 1 apps. Either upgrade to watchOS 2 apps, or use an older version of Xcode. (EmporiumWatchKitApp)

**Comment by chamons** [comment]
As noted in the error:

```
Xcode 10 does not support watchOS 1 apps. Either upgrade to watchOS 2 apps, or use an older version of Xcode. 
```

Your Xcode is too new for that sample.

From the section of the error you posted, I believe you are trying to build this sample:

```
./ios9/Emporium/EmporiumWatchKitApp
```

As noted by the folder structure, it was introduced in iOS 9.

If you want a more modern watchOS example I'd look at:

```
./watchOS/WatchKitCatalog/WatchApp3
```

We don't update older Xcode samples, just like Apple in this case.
