### ISSUE TITLE
WatchConnectivity Sample - help please

### ISSUE THREAD

**Issue by fullphat** [xamarin/ios-samples#399]
Hi there!

The WatchConnectivity Sample works perfectly, however I've tried to replicate the functionality in an application of my own and I can't get it to work in the simulator or on real hardware.

Everything seems ok. except that when the Watch app installs and launches, there is no "Connectivity with Watch" console output as there is with the sample code and, even though sending messages from the Phone app completes successfully, they don't seem to be received by the Watch app.

Appreciate this isn't much to go on, but any suggestions would be appreciated.

**Comment by fullphat** [comment]
I think I've fixed it.  See https://xamarin.github.io/bugzilla-archives/43/43533/bug.html

I added `WKExtensionDelegateClassName > ExtensionDelegate` to the WatchKitExtension's `Info.plist` and that seems to have done the job.

Hope this helps anyone else struggling - spent most of today stuck on this!

**Comment by chamons** [comment]
@fullphat - I'm glad you were able to figure this out, watchOS development isn't always easy.

Given that, is this still a sample issue or can I close it?

**Comment by fullphat** [comment]
Still having occasional issues but the sample works fine so please feel free to close the issue.  

WatchOS development is an absolute nightmare! 😂
