### ISSUE TITLE
Carplay Sample

### ISSUE THREAD

**Issue by zurtox** [xamarin/ios-samples#400]
I've been researching in a good way how to make an Audio Carplay sample, but unfortunately, I cannot make it in order to run it successfully.

I have the entitlements in order to run succesfully the app, but I have errors in the handlers and I have litterally no clue on how to call the player view when I tap the selected element.

I know that this method is called when selected:
```
public override void InitiatePlaybackOfContentItem(MPPlayableContentManager contentManager, NSIndexPath indexPath, Action<NSError> completionHandler)
{
    //base.InitiatePlaybackOfContentItem(contentManager, indexPath, completionHandler);
}
```
If anyone has an functional sample about it, I'll be fully grateful.

**Comment by whitneyschmidt** [comment]
@zurtox Unfortunately we don't have our own sample to point to at this time. You can find a partial sample here: https://github.com/Suplanus/Xamarin.Demo.Carplay

The README in that repo also contains a few links to resources that may be useful.
