### ISSUE TITLE
DidWriteData not being Called

### ISSUE THREAD

**Issue by Akinnagbe** [xamarin/ios-samples#406]
DidWriteData of UrlSessionDelegate in SimpleBackgroundTransfer in not being called, hence the percentage is not displaying on the UI.

**Comment by tj-devel709** [comment]
Hello,
I would first like to confirm that you are referring to the sample [here](https://github.com/xamarin/ios-samples/tree/main/SimpleBackgroundTransfer).

We are looking into this now, but we would like to know what environment you are using.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by chamons** [comment]
Alright, we were able to get to the bottom of this. @Akinnagbe no need for version info.

It looks like the sample _today_ requires either swapping to the non-interface base type (see #407) or adding the [Export] attributes you can get by typing override METHOD_NAME and letting intellisense complete it for you.

We are investigating if this is a regression (the sample is right and we broke behavior) or if the sample was written wrong. 

Until then, you can use the model NSUrlSessionDownloadDelegate or add an export.
