### ISSUE TITLE
ConvertedFrogScroller - pinch to zoom does not work with small images

### ISSUE THREAD

**Issue by fuzzylogicd** [xamarin/ios-samples#414]
ConvertedFrogScroller - The pinch to zoom functionality does not work when the image is small ( for example 300 x 300).

Pinch to zoom works fine with large images (for example image taken with iphone camera)

Any insight would be appreciated. Thank you

**Comment by rolfbjarne** [comment]
From the code it seems this is deliberate:

https://github.com/xamarin/ios-samples/blob/56aa9e2ea1e5e6236b588e37223a78539f7c9477/FrogScroller/FrogScroller/ImageScrollView.cs#L173-L175

In any case, please attach your complete sample (with small images) so that we're trying the same thing.

**Comment by mandel-macaque** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
