### ISSUE TITLE
intro-to-extensions not working.

### ISSUE THREAD

**Issue by Tymaku** [xamarin/ios-samples#416]
Xamarin.iOS 14.20.0.24 + iOS simulator 14.5. 
Sweeping screen down shows empty notification's panel.

**Comment by chamons** [comment]
Thanks for the report. I could reproduce it not showing up in the list.

Fixed in #417 - the extension now shows up. Though for modern cases you should look towards Widgets over Today extensions:

https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension
