### ISSUE TITLE
Doubts about the use class WCSessionManager

### ISSUE THREAD

**Issue by nowlights** [xamarin/ios-samples#418]
The WCSessionManager class was created in the WatchOSExtentsion project, and from what I saw there is no same class in the iOS project, how do I call this class that is in WatchOSExentsion by the iOS project?

**Comment by chamons** [comment]
Where is WCSessionManager documented by Apple? I see [WCSession](https://developer.apple.com/documentation/watchconnectivity/wcsession?language=objc) but don't see WatchOSExtentsion.

**Comment by nowlights** [comment]
from the project ios-samples/watchOS/WatchConnectivity/WatchConnectivity.OnWatchExtension

**Comment by chamons** [comment]
The [WCSessionDelegate](https://github.com/xamarin/xamarin-macios/blob/main/src/watchconnectivity.cs#L119) class is defined in the WatchConnectivity namespace.

Please provide more information on your specific issue.
