### ISSUE TITLE
Request: Sample with MFMailComposeViewController

### ISSUE THREAD

**Issue by scarabdesign** [xamarin/ios-samples#419]
Please make a sample project with the ability to send email with MFMailComposeViewController. 

I've been trying to get it to work with Xamarin iOS 15.0.0.6 and wondering if I'm doing it right. The compose window comes up, but after sending or trying to cancel, the window never leaves. It worked in iOS 14.5.

Having a sample project that concentrates on this aspect can help my troubleshoot my issues today and in the future.

**Comment by scarabdesign** [comment]
FYI, found out my issue, so I'm good to go, however, this sample would still be nice to have.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
