### ISSUE TITLE
ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources ImageView not Rendering

### ISSUE THREAD

**Issue by tj-devel709** [xamarin/ios-samples#424]
ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources has an issue where the UIImageView inside ConferenceVideoCell.cs does not render. In the screenshots, it appears that there should be a blue background, but the UIImageView does not show up. This occurs in the legacy sample and the dotnet sample

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
