### ISSUE TITLE
iOSTenThree  sample don't work well on iPad 

### ISSUE THREAD

**Issue by dingxiaolong** [xamarin/ios-samples#454]
When try to Switch  AlternateIcons on iPad , there is an error :
![image](https://user-images.githubusercontent.com/21192107/167121431-7bc03516-baf6-4191-b916-bd029ac187b8.png)
The demo include all the size of icon , and it work well on native , so I really don't know the reason .
Could you help check it please ,Many thanks .

**Comment by chamons** [comment]
Thanks for the feedback.

What specific sample did this code come from?

**Comment by dingxiaolong** [comment]
Thanks for you checking .
I have found the root cause now, info.plist in this sample don't support iPad .
Seems Xamarin have a strict check than native code .
