### ISSUE TITLE
Please Update CoreLocation to the latest iOS

### ISSUE THREAD

**Issue by gcadmes-extron** [xamarin/ios-samples#455]
The CoreLocation sample is for iOS 9.  There were major updates to Location Services in iOS 13.
Today, the iOS version is 15.4.1.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
