### ISSUE TITLE
if image dont exist

### ISSUE THREAD

**Issue by peterpab** [xamarin/ios-samples#469]
https://github.com/xamarin/ios-samples/blob/56aa9e2ea1e5e6236b588e37223a78539f7c9477/tvos/tvTable/Documentation/Doxyfile#L731

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
