### ISSUE TITLE
The iOS app UI snapshot is not updated when the Background task completes

### ISSUE THREAD

**Issue by AlexBrownShi** [xamarin/ios-samples#51]
If using the iOS Background upload or download, there is a CompletionHandler that must be called - it updates the APP snapshot that users see when switching apps.  However, my experience with this method is that when the task completes in the background, the app screenshot is NOT updated.  

How would we modify this BackgroundExecution example to support updating the app screenshot in the background?

**Comment by rzaitov** [comment]
I think you are interested in SimpleBackgroundTransfer sample:
https://github.com/xamarin/monotouch-samples/tree/master/SimpleBackgroundTransfer

Here the prof that iOS takes snapshot after completionHandler invocation. Paste the following code 
				InvokeOnMainThread (() => {
					var v = new UIView ();
					v.BackgroundColor = UIColor.Red;
					v.Frame = new CoreGraphics.CGRect (0, 0, 100, 100);
					appDelegate.Window.AddSubview (v);
					v.Center = appDelegate.Window.Center;
				});

just before the handler invocation:
https://github.com/xamarin/monotouch-samples/blob/bd9cefdd3e6eb028b65ab0be2a47ac6268e9e569/SimpleBackgroundTransfer/SimpleBackgroundTransfer/SimpleBackgroundTransferViewController.cs#L151

This will put red rectangle to window's hierarchy, then iOS will take snapshot, so you should be able to see red square in app switcher. Steps to reproduce:

* paste code before handler();
* run app
* press "Start"
* press Home button and wait
* go to app switcher

**Comment by AlexBrownShi** [comment]
Well, that is how I was doing it originally and it works great.  But it appears AirWatch app wrapping does not support creating your own NSURLSession with configuration (you must use SharedSession) so, I am now back to using the ModernHttpClient for the upload and using this older method of running a background task as in the BackgroundExecution example (which seems to work with airwatch).  One of the downsides is that it doesn't seem to give me a snapshot of the app when the task completes.  

Any ideas?

**Comment by rzaitov** [comment]
I am afraid that these are the only possible ways:
http://developer.xamarin.com/guides/ios/application_fundamentals/backgrounding/part_3_ios_backgrounding_techniques/updating_an_application_in_the_background/

**Comment by AlexBrownShi** [comment]
What do you mean?  Are you saying that the BackgroundExecution example method is no longer supported by Xamarin/iOS (I noticed the documentation was taken down off the site recently) or that it just doesn't update the app screen snapshot when completed?

**Comment by rzaitov** [comment]
Just to clarify we support all samples in this repo.
Looks like I wasn't clear in my previous comment, let me explain. As I understand you want to update UI while app in the background mode. The possible solutions are explained here:
http://developer.xamarin.com/guides/ios/application_fundamentals/backgrounding/part_3_ios_backgrounding_techniques/updating_an_application_in_the_background/

And I am afraid that there is no other way to update your UI while your app is working in background mode. But I am *not* 100% sure.

**Comment by AlexBrownShi** [comment]
The method of background execution outlined in the BackgroundExecution example is no longer documented on this page - it used to be as recent as a couple of months ago.  The code still works - but doesn't update that UI snapshot.  I mean updates to the UI still seem to execute, they just don't update the screenshot and are visible only when you switch back to the app. 

Does that make sense?  I want to make sure you understand the problem, but it sounds like you are saying that it is just not supported in that situation.

**Comment by rolfbjarne** [comment]
@AlexBrownShi were you ever able to figure out a solution to your problem? Or do you still need help?

**Comment by spouliot** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
