### ISSUE TITLE
[StreamingAudio] Port to an async/await approach, with proper cancellation support 

### ISSUE THREAD

**Issue by alanmcgovern** [xamarin/ios-samples#70]
Hey,

This is a first-draft at porting to async/await using CancellationTokens to help handle proper cleanup/destruction of the player and related resources. It makes it very very nice to use :)

https://gist.github.com/alanmcgovern/9275bf1159630756cebe

**Comment by olegoid** [comment]
@alanmcgovern your PR will be more than welcome :)

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
