### ISSUE TITLE
Don't call base in PrepareForSegue in CloudCaption sample

### ISSUE THREAD

**Issue by jgold6** [xamarin/ios-samples#78]
The CloudCaptions [1] sample throws an error due to a NullReferenceException in PrepareForSegue when you select the option to "Select from Cloudkit".

When you choose "Select from CloudKit", this is the method that is called:

UIAlertAction selectExisting = UIAlertAction.Create (selectButton, UIAlertActionStyle.Default, action => {
PerformSegue("selectExisting", null);
});

As you can see, null is passed in for the "sender" argument to the PerformSegue call, which triggers the PrepareForSegue method with those arguments, IOW null is being passed in as the sender. Anyway, they issue is that you should not need to call base in this override. IOW, just remove this line in the PrepareForSegue method:

base.PrepareForSegue (segue, sender);

According to Apple's docs: "The default implementation of this method does nothing."
so there is no need to call it.  

[1] https://docs.xamarin.com/samples/monotouch/ios8/CloudCaptions/

**Comment by rolfbjarne** [comment]
I can't reproduce this; I tried the "Select from CloudKit" option, and a breakpoint in PrepareForSegue was hit, so the apparently broken code path seems to be working now.
