### ISSUE TITLE
AUSoundTriggeredPlayingSoundMemoryBased doesn't work via bluetooth speaker

### ISSUE THREAD

**Issue by deadean** [xamarin/ios-samples#95]
What should I do to get it working?

**Comment by olegoid** [comment]
@deadean does it happens only with Xamarin.iOS SDK or native apps behave the same way?

**Comment by deadean** [comment]
@olegoid Yes, native apps have the same behaviour

**Comment by rolfbjarne** [comment]
If native apps behave the same way, there's not much we can do.
