### ISSUE TITLE
Pickers sample - UIPickerView doesn't show selected and non selected cells as one would expect

### ISSUE THREAD

**Issue by cfin-mt** [xamarin/ios-samples#97]
I've seen this in the simulator and a connected device. The appearance of items, both selected and non selected, seems pretty random. See attached image:

![image](https://cloud.githubusercontent.com/assets/19264489/17022452/efe158c2-4f45-11e6-9257-adeaeb9ed439.png)

Also worthy of note is I attempted to customize a UIPickerView myself before looking at these samples, and I'm facing similar issues with the appearance of the picker. Could this be an issue with overriding GetView()?

**Comment by rolfbjarne** [comment]
Yes, there's clearly something not quite right here.

This is the MonoCatalog-MonoDevelop sample, launch -> select "Pickers", then "Custom" and finally try scrolling the list.

**Comment by rolfbjarne** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs. In preparation for this, all issues and PRs in this repository are being closed.
